version: "3.9"

services:
  web:
    build: .
    container_name: haonhung.app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/tmp
      - gem-data:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - haonhung-networks
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    container_name: haonhung.mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - haonhung-networks

  redis:
    image: redis
    command: redis-server
    container_name: haonhung.redis
    volumes:
      - redis-data:/var/shared/redis
    networks:
      - haonhung-networks

networks:
  haonhung-networks:
    name: haonhung
    external: true

volumes:
  mysql_data:
  gem-data:
  redis-data:
